# Generated by Django 4.1.3 on 2022-12-15 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_crudapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudapp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
