# Generated by Django 4.1.3 on 2022-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_crudapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
